apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: mnist-train-dist
  namespace: default
spec:
  tfReplicaSpecs: # three different roles
    Chief:
      replicas: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - command:
                - /usr/local/bin/python
                - /opt/model.py # execute the same program, will distinguish the roles in the code using env var.
                - --tf-model-dir=$(modelDir)
                - --tf-export-dir=$(exportDir)
                - --tf-train-steps=$(trainSteps)
                - --tf-batch-size=$(batchSize)
                - --tf-learning-rate=$(learningRate)
              env:
                - name: modelDir
                  value: /mnt/my-model
                - name: exportDir
                  value: /mnt/my-model/export
                - name: trainSteps
                  value: "200"
                - name: batchSize
                  value: "100"
                - name: learningRate
                  value: "0.01"
              image: kubeflow/examples/mnist:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: nfs-pvc
                  mountPath: "/mnt"
              name: tensorflow
              workingDir: /opt
          restartPolicy: OnFailure
          volumes:
            - name: nfs-pvc
              persistentVolumeClaim:
                claimName: kubeflow-e2e-claim
    Ps:
      replicas: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - command:
                - /usr/local/bin/python
                - /opt/model.py
                - --tf-model-dir=$(modelDir)
                - --tf-export-dir=$(exportDir)
                - --tf-train-steps=$(trainSteps)
                - --tf-batch-size=$(batchSize)
                - --tf-learning-rate=$(learningRate)
              env:
                - name: modelDir
                  value: /mnt/my-model
                - name: exportDir
                  value: /mnt/my-model/export
                - name: trainSteps
                  value: "200"
                - name: batchSize
                  value: "100"
                - name: learningRate
                  value: "0.01"
              image: kubeflow/examples/mnist:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: nfs-pvc
                  mountPath: "/mnt"
              name: tensorflow
              workingDir: /opt
          restartPolicy: OnFailure
          volumes:
            - name: nfs-pvc
              persistentVolumeClaim:
                claimName: kubeflow-e2e-claim
    Worker:
      replicas: 2
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - command:
                - /usr/local/bin/python
                - /opt/model.py
                - --tf-model-dir=$(modelDir)
                - --tf-export-dir=$(exportDir)
                - --tf-train-steps=$(trainSteps)
                - --tf-batch-size=$(batchSize)
                - --tf-learning-rate=$(learningRate)
              env:
                - name: modelDir
                  value: /mnt/my-model
                - name: exportDir
                  value: /mnt/my-model/export
                - name: trainSteps
                  value: "200"
                - name: batchSize
                  value: "100"
                - name: learningRate
                  value: "0.01"
              image: kubeflow/examples/mnist:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: nfs-pvc
                  mountPath: "/mnt"
              name: tensorflow
              workingDir: /opt
          restartPolicy: OnFailure
          volumes:
            - name: nfs-pvc
              persistentVolumeClaim:
                claimName: kubeflow-e2e-claim
